### ISSUE TITLE
[Bug]: VSF application breaks after adding router.base

### ISSUE THREAD

**Issue by savina-chandla** [vuestorefront-community/spree#294] opened 2023-03-24 13:30 UTC
### Expected Behavior

I want to add route prefix to my vue storefront application integrated with Spree backend, so that it is served under a specific URL. I have tried using router.base in nuxt.config.js file but it breaks the VSF application(infinite loop) and api calls. 

 

### Actual Behavior

Application breaks with broken api calls after redirecting to another route appended by the router.base value. Screenshots below:![image](https://user-images.githubusercontent.com/89458320/227522086-37f1975c-faee-4d2d-a394-8fea61c8c056.png)

![image](https://user-images.githubusercontent.com/89458320/227522208-6cf3cd9e-3881-4dc2-bcec-92f0b0c1beda.png)

### Steps to reproduce

1 . Create .env file in packages/theme/.env
2 . Add following env variable in the .env file:
      
      API_BASE_URL=http://localhost:3000/api/
      VSF_STORE_URL=https://localhost:3000/shop/   
      VSF_MIDDLEWARE_URL=https://localhost:3000/shop/api/

3. The middleware.config.js is as below:

       module.exports = {
        integrations: {
          spree: {
            location: '@vue-storefront/spree-api/server',
            configuration: {
              backendUrl: 'https://demo.spreecommerce.org',
              assetsUrl: 'https://demo.spreecommerce.org',
              spreeFeatures: {
                ...defaultFeatures[process.env.SPREE_VERSION || 'spree43'],
                // Accepted wishlist values:
                // 'enabled' (Spree 4.4+)
                // 'legacy' (Spree older than 4.4 with spree_wishlist gem installed)
                // 'disabled' (Spree older than 4.4 without spree_wishlist gem)
                wishlist: 'disabled'
              }
            }
          }
        }
    
4. Update nuxt.config.js router object with the config as below: 
    
   
       router: {
          base: '/shop/',
          prefetchLinks: false,    
          extendRoutes(routes)
          {        
             getRoutes() .forEach((route) => routes.unshift(route));
          },    
       },

6. Run the app with yarn dev
7. Navigate to http://localhost:3000/ 

### What version of Spree integration are you using?

"@vue-storefront/spree": "1.3.0"

### What version of Node.js are you using?

14.17.0

### What browser (and version) are you using?

Chrome, Safari

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rafalcymerys** [comment] 2023-03-27 14:57
@savina-chandla please take a look at the latest version, where we've just merged a fix for this issue. Let us know if that solved the problem for you

**Closed by rafalcymerys** 2023-03-27 14:57 UTC
Labels: bug

**Comment by jatin-maropost** [comment] 2023-03-29 13:47
Thanks @rafalcymerys , This works now the issue is fixed
